Console: require ncurses as a curses implementation
multitextor uses termcap <term.h> (or terminfo) APIs like tgoto().
Some distributions provide it as part of -lcurses (like Fedore and
Ubuntu). But some don't (like Gentoo: https://bugs.gentoo.org/836155).

Cmake also does not enable it by default:
    https://gitlab.kitware.com/cmake/cmake/-/issues/23236

As a result on Gentoo multitextor build fails as:

    [ 60%] Linking CXX executable ../../_build/bin/multitextor
    ld: ../Console/libConsoleLib.a(ScreenTTY.cpp.o): undefined reference to symbol 'tgoto'
    ld: /lib64/libtinfo.so.6: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status

The change enables CURSES_NEED_NCURSES flag to pull in -ltinfo.